---
- name: Actualizar PHP
  hosts: servidores_app
  become: true
  tasks:
    - name: php_version_check
        command: php -v
        register: result
        ignore_errors: true

    - name: upgrade_php_to_8.2
      apt:
        name: php8.2
        state: latest
      when: result.stdout is defined and (result.stdout | regex_search('PHP (\\d+\\.\\d+)') | first | version_compare('8.2', '<'))
